simulation_params:
  dt: 0.001
  num_steps: 666
  gamma: 0.1
  mass: 1.0

  beta: 1.0                  # 1 / kBT

training_params:
  alpha: 2.0
  alpha_1: 1.0
  alpha_2: 0.1
  learning_rate: .01
  batch_size: 777
  training_iterations: 400

protocol_params:
  num_coefficients: 16

  a_endpoints: [5.0, 5.0]
  b_endpoints: [20.0, 20.0]
  c_endpoints: [0.0, 0.0]

save_directory: "/mnt/b/wsl_code/[JIM]-2025_09-Optimal_Control/protocolopt/testing_code/"  
'initilize_to_mc': True
'use_work_target': True
'use_adaptive_lr': True

report_frequency: 10
checkpoint_frequency: 100
plot_frequency: 200