blank_issues_enabled: false
contact_links:
  - name: Feature Request & Questions
    url: https://github.com/MathiasVanPatten/protocolopt/discussions
    about: Please share ideas or ask questions in the Discussions forum.